from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

from datetime import datetime


def generate_report(
    url,
    result,
    confidence,
    vt_result
):

    pdf = SimpleDocTemplate("report.pdf")

    styles = getSampleStyleSheet()

    content = []

    # Title

    title = Paragraph(
        "FishyWebAI Security Assessment Report",
        styles["Title"]
    )

    content.append(title)
    content.append(Spacer(1, 20))

    # Date

    current_time = datetime.now().strftime(
        "%d-%m-%Y %H:%M:%S"
    )

    content.append(
        Paragraph(
            f"<b>Generated:</b> {current_time}",
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 20))

    # Scan Information

    content.append(
        Paragraph(
            "<b>SCAN INFORMATION</b>",
            styles["Heading2"]
        )
    )

    content.append(Spacer(1, 10))

    content.append(
        Paragraph(
            f"<b>URL:</b> {url}",
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 8))

    content.append(
        Paragraph(
            f"<b>Result:</b> {result}",
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 8))

    content.append(
        Paragraph(
            f"<b>Confidence Score:</b> {confidence}%",
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 20))

    # Threat Intelligence

    content.append(
        Paragraph(
            "<b>THREAT INTELLIGENCE</b>",
            styles["Heading2"]
        )
    )

    content.append(Spacer(1, 10))

    content.append(
        Paragraph(
            vt_result,
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 20))

    # Conclusion

    content.append(
        Paragraph(
            "<b>ASSESSMENT SUMMARY</b>",
            styles["Heading2"]
        )
    )

    content.append(Spacer(1, 10))

    if "PHISHING" in result:

        summary = """
        The scanned website shows phishing-related indicators.
        Users should exercise caution before entering
        credentials or sensitive information.
        """

    else:

        summary = """
        No significant phishing indicators were detected
        during this scan. Continue following standard
        cybersecurity best practices.
        """

    content.append(
        Paragraph(
            summary,
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 30))

    content.append(
        Paragraph(
            "Generated by FishyWebAI",
            styles["Italic"]
        )
    )

    pdf.build(content)